---
version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.6
        environment:
          MIX_ENV: test
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_DB: changelog_test
          POSTGRES_PASSWORD: "postgres"

    working_directory: ~/workspace

    steps:
      - checkout
      - run:
          name: Install hex locally
          command: mix local.hex --force
      - run:
          name: Install rebar locally
          command:  mix local.rebar --force
      - run:
          name: Get all dependencies & compile
          command: mix do deps.get, compile
      - run:
          name: Wait for PostgreSQL
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: mix test
